# Generated by Django 5.0.6 on 2025-03-22 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0031_shipmentitem_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(blank=True, max_length=255, null=True)),
                ('lot_number', models.IntegerField(blank=True, null=True)),
                ('waybill_number', models.IntegerField(blank=True, null=True)),
                ('moisture', models.CharField(blank=True, max_length=255, null=True)),
                ('total_seed_heat_damage', models.CharField(blank=True, max_length=255, null=True)),
                ('heat_damage_kernels', models.CharField(blank=True, max_length=255, null=True)),
                ('bran', models.CharField(blank=True, max_length=255, null=True)),
                ('broken', models.CharField(blank=True, max_length=255, null=True)),
                ('total_ash', models.CharField(blank=True, max_length=255, null=True)),
                ('acid_insoluble_ash', models.CharField(blank=True, max_length=255, null=True)),
                ('volatile_oil', models.CharField(blank=True, max_length=255, null=True)),
                ('nonvolatile_oil', models.CharField(blank=True, max_length=255, null=True)),
                ('extraneous_matter', models.CharField(blank=True, max_length=255, null=True)),
                ('purity', models.CharField(blank=True, max_length=255, null=True)),
                ('total_excrta', models.CharField(blank=True, max_length=255, null=True)),
                ('whole_insect_dead', models.CharField(blank=True, max_length=255, null=True)),
                ('curcumin', models.CharField(blank=True, max_length=255, null=True)),
                ('pungency', models.CharField(blank=True, max_length=255, null=True)),
                ('thorugh_1_mm', models.CharField(blank=True, max_length=255, null=True)),
                ('thorugh_1point7_mm', models.CharField(blank=True, max_length=255, null=True)),
                ('through_180_u', models.CharField(blank=True, max_length=255, null=True)),
                ('through_425_u', models.CharField(blank=True, max_length=255, null=True)),
                ('through_500_u', models.CharField(blank=True, max_length=255, null=True)),
                ('through_600_u', models.CharField(blank=True, max_length=255, null=True)),
                ('through_18_mesh', models.CharField(blank=True, max_length=255, null=True)),
                ('through_25_mesh', models.CharField(blank=True, max_length=255, null=True)),
                ('total_plate_count', models.CharField(blank=True, max_length=255, null=True)),
                ('yeast_mold_count', models.CharField(blank=True, max_length=255, null=True)),
                ('e_coli', models.CharField(blank=True, max_length=255, null=True)),
                ('salmonella', models.CharField(blank=True, max_length=255, null=True)),
                ('heavy_metal', models.CharField(blank=True, max_length=255, null=True)),
                ('aflatoxim_B1', models.CharField(blank=True, max_length=255, null=True)),
                ('aflatoxin_B1_B2_G1_G2', models.CharField(blank=True, max_length=255, null=True)),
                ('ochratoxin', models.CharField(blank=True, max_length=255, null=True)),
                ('total_parameters', models.CharField(blank=True, max_length=255, null=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item_specification', to='contracts.shipmentitem')),
            ],
        ),
    ]
