# Generated by Django 5.0.6 on 2025-03-22 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0032_itemspecification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemspecification',
            old_name='total_excrta',
            new_name='total_excreta',
        ),
    ]
