# Generated by Django 5.0.6 on 2025-03-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0033_rename_total_excrta_itemspecification_total_excreta'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemspecification',
            name='other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
