# Generated by Django 5.0.6 on 2025-03-22 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0034_itemspecification_other'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemspecification',
            old_name='aflatoxim_B1',
            new_name='aflatoxin_B1',
        ),
    ]
