# Generated by Django 5.0.6 on 2025-03-22 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0035_rename_aflatoxim_b1_itemspecification_aflatoxin_b1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemspecification',
            old_name='thorugh_1_mm',
            new_name='through_1_mm',
        ),
        migrations.RenameField(
            model_name='itemspecification',
            old_name='thorugh_1point7_mm',
            new_name='through_1point7_mm',
        ),
    ]
