# Generated by Django 5.0.6 on 2025-04-07 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0036_rename_thorugh_1_mm_itemspecification_through_1_mm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentitem',
            name='item_category',
            field=models.CharField(choices=[('Crop', 'Crop'), ('Spices', 'Spices')], default='Crop', max_length=255),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='item_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='supplier_entity_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='supplier_type',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='itemspecification',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_specification', to='contracts.shipmentitem'),
        ),
    ]
