# Generated by Django 5.0.6 on 2025-04-08 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0037_shipmentitem_item_category_shipmentitem_item_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemspecification',
            name='customer_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_cont', to='contracts.admincustomercontract'),
        ),
        migrations.AddField(
            model_name='itemspecification',
            name='processor_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_cont', to='contracts.adminprocessorcontract'),
        ),
    ]
