# Generated by Django 5.0.6 on 2025-04-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0038_itemspecification_customer_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropdetails',
            name='lot_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropdetails',
            name='waybill_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
