# Generated by Django 5.0.6 on 2025-04-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0039_cropdetails_lot_number_cropdetails_waybill_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemspecification',
            name='chalky',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemspecification',
            name='red_damage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
