# Generated by Django 5.0.6 on 2025-04-08 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0040_itemspecification_chalky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropdetails',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.shipmentitem'),
        ),
    ]
