# Generated by Django 5.0.6 on 2025-04-16 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0041_cropdetails_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropdetails',
            name='item_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customercontractcropdetails',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.shipmentitem'),
        ),
        migrations.AddField(
            model_name='customercontractcropdetails',
            name='item_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
