# Generated by Django 5.0.6 on 2025-04-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0042_cropdetails_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercontractcropdetails',
            name='lot_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customercontractcropdetails',
            name='waybill_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
