# Generated by Django 5.0.6 on 2025-04-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0044_delete_itemspecification'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentitem',
            name='supplier_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
