# Generated by Django 5.0.6 on 2025-04-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0045_shipmentitem_supplier_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropdetails',
            name='item_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropdetails',
            name='item_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customercontractcropdetails',
            name='item_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customercontractcropdetails',
            name='item_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
