# Generated by Django 5.0.6 on 2025-08-23 06:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0046_cropdetails_item_description_cropdetails_item_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprocessorcontract',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='cropdetails',
            name='per_unit_rate',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
