# Generated by Django 5.0.6 on 2025-08-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0047_alter_adminprocessorcontract_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincustomercontractdocuments',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminprocessorcontractdocuments',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
