# Generated by Django 5.0.6 on 2025-09-25 07:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0048_admincustomercontractdocuments_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincustomercontract',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
        migrations.AlterField(
            model_name='adminprocessorcontract',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
        migrations.AlterField(
            model_name='customercontractcropdetails',
            name='per_unit_rate',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='per_unit_price',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
