# Generated by Django 5.0.6 on 2024-08-26 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBroker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fein', models.CharField(blank=True, max_length=250, null=True, verbose_name='FEIN')),
                ('entity_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Entity Name')),
                ('billing_address', models.TextField(blank=True, null=True, verbose_name='Billing Address')),
                ('shipping_address', models.TextField(blank=True, null=True, verbose_name='Shipping Address')),
                ('main_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='Main Number')),
                ('main_fax', models.CharField(blank=True, max_length=250, null=True, verbose_name='Main Fax')),
                ('website', models.TextField(blank=True, null=True, verbose_name='Website')),
                ('gin_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='Gin Id')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessorDistributorShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor_id', models.CharField(blank=True, max_length=10, null=True)),
                ('processor_type', models.CharField(blank=True, max_length=5, null=True)),
                ('processor_entity_name', models.CharField(blank=True, max_length=255, null=True)),
                ('carrier_name', models.CharField(choices=[('Rail Car', 'Rail Car'), ('Truck/Trailer', 'Truck/Trailer')], max_length=15)),
                ('outbound_type', models.CharField(choices=[('Domestic', 'Domestic'), ('International', 'International')], max_length=15)),
                ('outbound_date', models.DateTimeField(auto_now_add=True)),
                ('carrier_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('purchase_order_name', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_order_number', models.CharField(blank=True, max_length=255, null=True)),
                ('carrier_id', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.CharField(blank=True, max_length=255, null=True)),
                ('gross_weight', models.CharField(blank=True, max_length=255, null=True)),
                ('net_weight', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_weight_left', models.CharField(blank=True, max_length=255, null=True)),
                ('lot_number', models.CharField(blank=True, max_length=255, null=True)),
                ('border_receive_date', models.DateTimeField(blank=True, null=True)),
                ('border_leaving_date', models.DateTimeField(blank=True, null=True)),
                ('customer_receive_date', models.DateTimeField(blank=True, null=True)),
                ('customer_leaving_date', models.DateTimeField(blank=True, null=True)),
                ('border_receive_date2', models.DateTimeField(blank=True, null=True)),
                ('border_leaving_date2', models.DateTimeField(blank=True, null=True)),
                ('warehouse_receive_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_entity_name', models.CharField(blank=True, max_length=255, null=True)),
                ('distributor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('distributor_entity_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomBrokerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Contact Name')),
                ('contact_email', models.CharField(blank=True, max_length=250, null=True, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='Contact Phone')),
                ('contact_fax', models.CharField(blank=True, max_length=250, null=True, verbose_name='Contact Fax')),
                ('p_password_raw', models.CharField(blank=True, max_length=250, null=True)),
                ('custom_broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouseManagement.custombroker', verbose_name='Select Custom broker')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessorDistributorShipmentDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(blank=True, max_length=255, null=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='processor_distributor_shipment/file/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouseManagement.processordistributorshipment')),
            ],
        ),
    ]
