# Generated by Django 5.0.6 on 2024-09-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0002_paymentforshipment_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.IntegerField(blank=True, default=30),
        ),
    ]
