# Generated by Django 5.0.6 on 2024-09-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0003_customer_credit_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='credit_limit',
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_terms',
            field=models.IntegerField(choices=[('0', 'Pay on invoice receipt'), ('0', 'Pay while ordering'), ('30', '30 days'), ('60', '60 days'), ('90', '90 days')], default=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_tax_payable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
