# Generated by Django 5.0.6 on 2024-08-27 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0003_warehouse_remove_custombrokeruser_custom_broker_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distributor',
            old_name='name',
            new_name='entity_name',
        ),
        migrations.RenameField(
            model_name='processordistributorshipment',
            old_name='border_leaving_date2',
            new_name='border_back_leaving_date',
        ),
        migrations.RenameField(
            model_name='processordistributorshipment',
            old_name='border_receive_date2',
            new_name='border_back_receive_date',
        ),
        migrations.RenameField(
            model_name='processordistributorshipment',
            old_name='carrier_name',
            new_name='carrier_type',
        ),
        migrations.RenameField(
            model_name='processordistributorshipment',
            old_name='outbound_date',
            new_name='date_pulled',
        ),
        migrations.RenameField(
            model_name='processordistributorshipment',
            old_name='customer_leaving_date',
            new_name='distributor_leaving_date',
        ),
        migrations.RenameField(
            model_name='processordistributorshipment',
            old_name='customer_receive_date',
            new_name='distributor_receive_date',
        ),
        migrations.RenameField(
            model_name='processordistributorshipment',
            old_name='carrier_quantity',
            new_name='ship_quantity',
        ),
        migrations.RemoveField(
            model_name='processordistributorshipment',
            name='carrier_id',
        ),
        migrations.RemoveField(
            model_name='processordistributorshipment',
            name='customer_entity_name',
        ),
        migrations.RemoveField(
            model_name='processordistributorshipment',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='processordistributorshipment',
            name='warehouse_receive_date',
        ),
        migrations.RemoveField(
            model_name='processordistributorshipment',
            name='weight',
        ),
        migrations.AddField(
            model_name='processordistributorshipment',
            name='processor_receive_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CarrierDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_carrier', to='warehouseManagement.processordistributorshipment')),
            ],
        ),
    ]
