# Generated by Django 5.0.6 on 2024-09-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0004_remove_customer_credit_limit_customer_credit_terms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_terms',
            field=models.IntegerField(choices=[(0, 'Pay on invoice receipt'), (0, 'Pay while ordering'), (30, '30 days'), (60, '60 days'), (90, '90 days')], default=30),
        ),
    ]
