# Generated by Django 5.0.6 on 2024-08-27 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0004_rename_name_distributor_entity_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessorWarehouseShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor_id', models.CharField(blank=True, max_length=10, null=True)),
                ('processor_type', models.CharField(blank=True, max_length=5, null=True)),
                ('processor_entity_name', models.CharField(blank=True, max_length=255, null=True)),
                ('carrier_type', models.CharField(choices=[('Rail Car', 'Rail Car'), ('Truck/Trailer', 'Truck/Trailer')], max_length=15)),
                ('outbound_type', models.CharField(choices=[('Domestic', 'Domestic'), ('International', 'International')], max_length=15)),
                ('date_pulled', models.DateTimeField(auto_now_add=True)),
                ('purchase_order_name', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_order_number', models.CharField(blank=True, max_length=255, null=True)),
                ('lot_number', models.CharField(blank=True, max_length=255, null=True)),
                ('ship_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('gross_weight', models.CharField(blank=True, max_length=255, null=True)),
                ('net_weight', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_weight_left', models.CharField(blank=True, max_length=255, null=True)),
                ('border_receive_date', models.DateTimeField(blank=True, null=True)),
                ('border_leaving_date', models.DateTimeField(blank=True, null=True)),
                ('distributor_receive_date', models.DateTimeField(blank=True, null=True)),
                ('distributor_leaving_date', models.DateTimeField(blank=True, null=True)),
                ('border_back_receive_date', models.DateTimeField(blank=True, null=True)),
                ('border_back_leaving_date', models.DateTimeField(blank=True, null=True)),
                ('processor_receive_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('distributor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('distributor_entity_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('warehouse_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='carrierdetails',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_carrier', to='warehouseManagement.processorwarehouseshipment'),
        ),
        migrations.AlterField(
            model_name='processordistributorshipmentdocuments',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouseManagement.processorwarehouseshipment'),
        ),
        migrations.DeleteModel(
            name='ProcessorDistributorShipment',
        ),
    ]
