# Generated by Django 5.0.6 on 2024-09-08 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0005_alter_customer_credit_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='processorwarehouseshipment',
            name='crop',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='warehousecustomershipment',
            name='crop',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='warehousecustomershipment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouseManagement.warehouseorder'),
        ),
    ]
