# Generated by Django 5.0.6 on 2024-08-27 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0005_processorwarehouseshipment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_request_id', models.IntegerField()),
                ('invoice_date', models.DateTimeField()),
                ('processor_id', models.IntegerField()),
                ('sub_total', models.CharField(blank=True, max_length=255, null=True)),
                ('tax', models.CharField(blank=True, max_length=255, null=True)),
                ('final_total', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('quantity_received', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='processorwarehouseshipment',
            name='warehouse_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processorwarehouseshipment',
            name='weight_unit',
            field=models.CharField(choices=[('LBS', 'LBS'), ('MT', 'MT')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.CharField(blank=True, max_length=255, null=True)),
                ('weight_unit', models.CharField(choices=[('LBS', 'LBS'), ('MT', 'MT')], max_length=10)),
                ('per_unit_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_total_cost', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_item', to='warehouseManagement.warehouseorder')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('final_stock', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_stock', to='warehouseManagement.warehouseorder')),
            ],
        ),
    ]
