# Generated by Django 5.0.6 on 2024-09-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0006_processorwarehouseshipment_crop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processorwarehouseshipment',
            name='crop_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='warehousecustomershipment',
            name='crop_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
