# Generated by Django 5.0.6 on 2024-08-27 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0007_processorwarehouseshipment_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Contact Name')),
                ('contact_email', models.CharField(blank=True, max_length=250, null=True, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='Contact Phone')),
                ('contact_fax', models.CharField(blank=True, max_length=250, null=True, verbose_name='Contact Fax')),
                ('p_password_raw', models.CharField(blank=True, max_length=250, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouseManagement.customer', verbose_name='Select Customer')),
            ],
        ),
    ]
