# Generated by Django 5.0.6 on 2024-09-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0008_warehousecustomershipment_approval_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseshipmentlog',
            name='changes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
