# Generated by Django 5.0.6 on 2024-08-29 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_rename_admincustomersignature_admincustomercontractsignature'),
        ('warehouseManagement', '0008_customer_customeruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='processorwarehouseshipment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_delivery', to='warehouseManagement.warehouseorder'),
        ),
        migrations.AddField(
            model_name='processorwarehouseshipment',
            name='processor_sku_list',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processorwarehouseshipment',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_delivery', to='contracts.adminprocessorcontract'),
        ),
        migrations.AlterField(
            model_name='warehousestock',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_stock', to='warehouseManagement.warehouseorder'),
        ),
    ]
