# Generated by Django 5.0.6 on 2024-08-29 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_rename_admincustomersignature_admincustomercontractsignature'),
        ('warehouseManagement', '0009_processorwarehouseshipment_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseorder',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_order', to='contracts.adminprocessorcontract'),
        ),
        migrations.AlterField(
            model_name='warehouseorder',
            name='invoice_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warehouseorder',
            name='invoice_request_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warehouseorder',
            name='processor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
