# Generated by Django 5.0.6 on 2024-09-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0009_warehouseshipmentlog_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='processorshipmentlog',
            name='changes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processorwarehouseshipment',
            name='approval_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processorwarehouseshipment',
            name='invoice_approval',
            field=models.BooleanField(default=False),
        ),
    ]
