# Generated by Django 5.0.6 on 2025-02-28 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0009_processorwarehouseshipment_qr_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseshipmentlotnumbertracking',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='warehouseshipmentlotnumbertracking',
            name='shipment',
        ),
        migrations.CreateModel(
            name='ProcessorShipmentDiversionTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill_number', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('diversion_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouseManagement.processorshipmentcrops')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouseManagement.processorwarehouseshipment')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseShipmentDiversionTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill_number', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('diversion_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouseManagement.warehouseshipmentcrops')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouseManagement.warehousecustomershipment')),
            ],
        ),
        migrations.DeleteModel(
            name='ProcessorShipmentLotNumberTracking',
        ),
        migrations.DeleteModel(
            name='WarehouseShipmentLotNumberTracking',
        ),
    ]
