# Generated by Django 5.0.6 on 2024-08-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0010_warehouseorder_contract_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProcessorDistributorShipmentDocuments',
            new_name='ProcessorWarehouseShipmentDocuments',
        ),
    ]
