# Generated by Django 5.0.6 on 2025-02-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0010_remove_warehouseshipmentlotnumbertracking_crop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processorshipmentcrops',
            name='waybill_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='warehouseshipmentcrops',
            name='waybill_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
