# Generated by Django 5.0.6 on 2025-03-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0011_processorshipmentcrops_waybill_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processorshipmentcrops',
            name='received_weight_lbs',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processorshipmentcrops',
            name='received_weight_mt',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processorshipmentcrops',
            name='shipped_weight_lbs',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processorshipmentcrops',
            name='shipped_weight_mt',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processorshipmentcrops',
            name='variation_weight_lbs',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processorshipmentcrops',
            name='variation_weight_mt',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processorwarehouseshipment',
            name='USDA_inspected',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processorwarehouseshipment',
            name='added_to_the_pool',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processorwarehouseshipment',
            name='border_exchange',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processorwarehouseshipment',
            name='departed_lacassine',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processorwarehouseshipment',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processorwarehouseshipment',
            name='discharged',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processorwarehouseshipment',
            name='phyto_cert_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processorwarehouseshipment',
            name='placed_at_industry_client',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processorwarehouseshipment',
            name='placed_at_industry_processor',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processorwarehouseshipment',
            name='processor_invoice_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processorwarehouseshipment',
            name='processor_invoice_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processorwarehouseshipment',
            name='railcar_loaded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processorwarehouseshipment',
            name='released_from_industry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processorwarehouseshipment',
            name='released_from_the_pool',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processorwarehouseshipment',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processorwarehouseshipment',
            name='returned_to_border_exchange',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processorwarehouseshipment',
            name='seal_numbers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processorwarehouseshipment',
            name='waybill_submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
