# Generated by Django 5.0.6 on 2024-08-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0011_rename_processordistributorshipmentdocuments_processorwarehouseshipmentdocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='processorwarehouseshipment',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processorwarehouseshipment',
            name='warehouse_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
