# Generated by Django 5.0.6 on 2024-09-09 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0012_processorshipmentlog_updated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='customer_documents/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouseManagement.customer')),
            ],
        ),
    ]
