# Generated by Django 5.0.6 on 2025-03-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0012_processorshipmentcrops_received_weight_lbs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processorshipmentcrops',
            name='received_weight',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
    ]
