# Generated by Django 5.0.6 on 2024-08-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0012_processorwarehouseshipment_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processorwarehouseshipment',
            name='border_back_leaving_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processorwarehouseshipment',
            name='border_back_receive_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processorwarehouseshipment',
            name='border_leaving_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processorwarehouseshipment',
            name='border_receive_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processorwarehouseshipment',
            name='distributor_leaving_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processorwarehouseshipment',
            name='distributor_receive_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processorwarehouseshipment',
            name='processor_receive_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
