# Generated by Django 5.0.6 on 2024-08-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0013_alter_processorwarehouseshipment_border_back_leaving_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processorwarehouseshipment',
            name='status',
            field=models.CharField(blank=True, choices=[('Released', 'Released'), ('At Border', 'At Border'), ('Crossed Border', 'Crossed Border'), ('Received', 'Received'), ('Released/Received', 'Released/Received')], max_length=255, null=True),
        ),
    ]
