# Generated by Django 5.0.6 on 2025-03-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0013_processorshipmentcrops_received_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processorshipmentcrops',
            name='contract_weight_left',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processorshipmentcrops',
            name='gross_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processorshipmentcrops',
            name='net_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processorshipmentcrops',
            name='received_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processorshipmentcrops',
            name='received_weight_lbs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processorshipmentcrops',
            name='received_weight_mt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processorshipmentcrops',
            name='ship_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processorshipmentcrops',
            name='shipped_weight_lbs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processorshipmentcrops',
            name='shipped_weight_mt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processorshipmentcrops',
            name='variation_weight_lbs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processorshipmentcrops',
            name='variation_weight_mt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warehouseshipmentcrops',
            name='contract_weight_left',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warehouseshipmentcrops',
            name='gross_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warehouseshipmentcrops',
            name='net_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warehouseshipmentcrops',
            name='ship_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
