# Generated by Django 5.0.6 on 2025-03-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0014_alter_processorshipmentcrops_contract_weight_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processorwarehouseshipment',
            name='no_of_days_at_facility',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processorwarehouseshipment',
            name='no_of_days_on_rail',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processorwarehouseshipment',
            name='no_of_days_to_border',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processorwarehouseshipment',
            name='no_of_days_to_lacassine',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
