# Generated by Django 5.0.6 on 2024-09-03 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0014_alter_processorwarehouseshipment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessorShipmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_log', to='warehouseManagement.processorwarehouseshipment')),
            ],
        ),
    ]
