# Generated by Django 5.0.6 on 2024-09-10 07:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0014_alter_paymentforshipment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdocuments',
            name='document_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customerdocuments',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
