# Generated by Django 5.0.6 on 2024-09-03 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0015_processorshipmentlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processorshipmentlog',
            name='field',
        ),
    ]
