# Generated by Django 5.0.6 on 2025-03-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0015_processorwarehouseshipment_no_of_days_at_facility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processorwarehouseshipment',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
