# Generated by Django 5.0.6 on 2024-09-04 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_admincustomercontract_customer_name'),
        ('warehouseManagement', '0016_remove_processorshipmentlog_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseCustomerShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_id', models.CharField(blank=True, max_length=255, null=True)),
                ('warehouse_name', models.CharField(blank=True, max_length=255, null=True)),
                ('distributor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('distributor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('carrier_type', models.CharField(choices=[('Rail Car', 'Rail Car'), ('Truck/Trailer', 'Truck/Trailer')], max_length=15)),
                ('outbound_type', models.CharField(choices=[('Domestic', 'Domestic'), ('International', 'International')], max_length=15)),
                ('date_pulled', models.DateTimeField(auto_now_add=True)),
                ('purchase_order_name', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_order_number', models.CharField(blank=True, max_length=255, null=True)),
                ('lot_number', models.CharField(blank=True, max_length=255, null=True)),
                ('ship_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('gross_weight', models.CharField(blank=True, max_length=255, null=True)),
                ('net_weight', models.CharField(blank=True, max_length=255, null=True)),
                ('weight_unit', models.CharField(choices=[('LBS', 'LBS'), ('MT', 'MT')], max_length=10)),
                ('contract_weight_left', models.CharField(blank=True, max_length=255, null=True)),
                ('border_receive_date', models.DateField(blank=True, null=True)),
                ('border_leaving_date', models.DateField(blank=True, null=True)),
                ('customer_receive_date', models.DateField(blank=True, null=True)),
                ('customer_leaving_date', models.DateField(blank=True, null=True)),
                ('border_back_receive_date', models.DateField(blank=True, null=True)),
                ('border_back_leaving_date', models.DateField(blank=True, null=True)),
                ('warehouse_receive_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Released', 'Released'), ('At Border', 'At Border'), ('Crossed Border', 'Crossed Border'), ('Received', 'Received'), ('Released/Received', 'Released/Received')], max_length=255, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.admincustomercontract')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseCustomerShipmentDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(blank=True, max_length=255, null=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='warehouse_shipment/file/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouseManagement.processorwarehouseshipment')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseShipmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipmentLog', to='warehouseManagement.warehousecustomershipment')),
            ],
        ),
    ]
