# Generated by Django 5.0.6 on 2025-04-16 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0044_delete_itemspecification'),
        ('warehouseManagement', '0016_processorwarehouseshipment_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousecustomershipment',
            name='USDA_inspected',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousecustomershipment',
            name='added_to_the_pool',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousecustomershipment',
            name='border_exchange',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousecustomershipment',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousecustomershipment',
            name='departed_lacassine',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousecustomershipment',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='warehousecustomershipment',
            name='discharged',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousecustomershipment',
            name='no_of_days_at_facility',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousecustomershipment',
            name='no_of_days_on_rail',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousecustomershipment',
            name='no_of_days_to_border',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousecustomershipment',
            name='no_of_days_to_lacassine',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousecustomershipment',
            name='phyto_cert_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousecustomershipment',
            name='placed_at_industry_client',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousecustomershipment',
            name='placed_at_industry_processor',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousecustomershipment',
            name='processor_invoice_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousecustomershipment',
            name='processor_invoice_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='warehousecustomershipment',
            name='railcar_loaded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousecustomershipment',
            name='released_from_industry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousecustomershipment',
            name='released_from_the_pool',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousecustomershipment',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousecustomershipment',
            name='returned_to_border_exchange',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousecustomershipment',
            name='seal_numbers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='warehousecustomershipment',
            name='waybill_submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouseshipmentcrops',
            name='received_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouseshipmentcrops',
            name='received_weight_lbs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouseshipmentcrops',
            name='received_weight_mt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouseshipmentcrops',
            name='shipped_weight_lbs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouseshipmentcrops',
            name='shipped_weight_mt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouseshipmentcrops',
            name='variation_weight_lbs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouseshipmentcrops',
            name='variation_weight_mt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ItemSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(blank=True, max_length=255, null=True)),
                ('lot_number', models.IntegerField(blank=True, null=True)),
                ('waybill_number', models.IntegerField(blank=True, null=True)),
                ('moisture', models.CharField(blank=True, max_length=255, null=True)),
                ('total_seed_heat_damage', models.CharField(blank=True, max_length=255, null=True)),
                ('heat_damage_kernels', models.CharField(blank=True, max_length=255, null=True)),
                ('bran', models.CharField(blank=True, max_length=255, null=True)),
                ('broken', models.CharField(blank=True, max_length=255, null=True)),
                ('chalky', models.CharField(blank=True, max_length=255, null=True)),
                ('red_damage', models.CharField(blank=True, max_length=255, null=True)),
                ('other', models.CharField(blank=True, max_length=255, null=True)),
                ('total_ash', models.CharField(blank=True, max_length=255, null=True)),
                ('acid_insoluble_ash', models.CharField(blank=True, max_length=255, null=True)),
                ('volatile_oil', models.CharField(blank=True, max_length=255, null=True)),
                ('nonvolatile_oil', models.CharField(blank=True, max_length=255, null=True)),
                ('extraneous_matter', models.CharField(blank=True, max_length=255, null=True)),
                ('purity', models.CharField(blank=True, max_length=255, null=True)),
                ('total_excreta', models.CharField(blank=True, max_length=255, null=True)),
                ('whole_insect_dead', models.CharField(blank=True, max_length=255, null=True)),
                ('curcumin', models.CharField(blank=True, max_length=255, null=True)),
                ('pungency', models.CharField(blank=True, max_length=255, null=True)),
                ('through_1_mm', models.CharField(blank=True, max_length=255, null=True)),
                ('through_1point7_mm', models.CharField(blank=True, max_length=255, null=True)),
                ('through_180_u', models.CharField(blank=True, max_length=255, null=True)),
                ('through_425_u', models.CharField(blank=True, max_length=255, null=True)),
                ('through_500_u', models.CharField(blank=True, max_length=255, null=True)),
                ('through_600_u', models.CharField(blank=True, max_length=255, null=True)),
                ('through_18_mesh', models.CharField(blank=True, max_length=255, null=True)),
                ('through_25_mesh', models.CharField(blank=True, max_length=255, null=True)),
                ('total_plate_count', models.CharField(blank=True, max_length=255, null=True)),
                ('yeast_mold_count', models.CharField(blank=True, max_length=255, null=True)),
                ('e_coli', models.CharField(blank=True, max_length=255, null=True)),
                ('salmonella', models.CharField(blank=True, max_length=255, null=True)),
                ('heavy_metal', models.CharField(blank=True, max_length=255, null=True)),
                ('aflatoxin_B1', models.CharField(blank=True, max_length=255, null=True)),
                ('aflatoxin_B1_B2_G1_G2', models.CharField(blank=True, max_length=255, null=True)),
                ('ochratoxin', models.CharField(blank=True, max_length=255, null=True)),
                ('total_parameters', models.CharField(blank=True, max_length=255, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_specification', to='contracts.shipmentitem')),
                ('processor_shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processor_ship', to='warehouseManagement.processorwarehouseshipment')),
                ('warehouse_shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_ship', to='warehouseManagement.warehousecustomershipment')),
            ],
        ),
    ]
