# Generated by Django 5.0.6 on 2024-09-04 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0017_warehousecustomershipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousecustomershipmentdocuments',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouseManagement.warehousecustomershipment'),
        ),
        migrations.CreateModel(
            name='CarrierDetails2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_shipment_carrier', to='warehouseManagement.warehousecustomershipment')),
            ],
        ),
    ]
