# Generated by Django 5.0.6 on 2025-04-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0018_carriers'),
    ]

    operations = [
        migrations.AddField(
            model_name='processorshipmentdiversiontracking',
            name='net_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processorshipmentdiversiontracking',
            name='prev_waybill_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processorshipmentdiversiontracking',
            name='weight_unit',
            field=models.CharField(choices=[('LBS', 'LBS'), ('MT', 'MT')], default='LBS', max_length=10),
        ),
        migrations.AddField(
            model_name='warehouseshipmentdiversiontracking',
            name='net_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouseshipmentdiversiontracking',
            name='prev_waybill_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='warehouseshipmentdiversiontracking',
            name='weight_unit',
            field=models.CharField(choices=[('LBS', 'LBS'), ('MT', 'MT')], default='LBS', max_length=10),
        ),
    ]
