# Generated by Django 5.0.6 on 2025-04-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0019_processorshipmentdiversiontracking_net_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrierdetails',
            name='carrier_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carrierdetails',
            name='carrier_type',
            field=models.CharField(choices=[('Rail Car', 'Rail Car'), ('Truck/Trailer', 'Truck/Trailer')], default='Rail Car', max_length=15),
        ),
        migrations.AddField(
            model_name='carrierdetails2',
            name='carrier_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carrierdetails2',
            name='carrier_type',
            field=models.CharField(choices=[('Rail Car', 'Rail Car'), ('Truck/Trailer', 'Truck/Trailer')], default='Rail Car', max_length=15),
        ),
    ]
