# Generated by Django 5.0.6 on 2025-04-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0020_carrierdetails_carrier_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processorshipmentcrops',
            name='item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='warehouseshipmentcrops',
            name='item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
