# Generated by Django 5.0.6 on 2025-04-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0021_processorshipmentcrops_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrierdetails',
            name='carrier_type',
            field=models.CharField(choices=[('Rail Car', 'Rail Car'), ('Truck/Trailer', 'Truck/Trailer'), ('Container/Vessel', 'Container/Vessel')], default='Rail Car', max_length=20),
        ),
        migrations.AlterField(
            model_name='carrierdetails2',
            name='carrier_type',
            field=models.CharField(choices=[('Rail Car', 'Rail Car'), ('Truck/Trailer', 'Truck/Trailer'), ('Container/Vessel', 'Container/Vessel')], default='Rail Car', max_length=20),
        ),
        migrations.AlterField(
            model_name='carriers',
            name='type',
            field=models.CharField(choices=[('Rail Car', 'Rail Car'), ('Truck/Trailer', 'Truck/Trailer'), ('Container/Vessel', 'Container/Vessel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='processorwarehouseshipment',
            name='carrier_type',
            field=models.CharField(choices=[('Rail Car', 'Rail Car'), ('Truck/Trailer', 'Truck/Trailer'), ('Container/Vessel', 'Container/Vessel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='warehousecustomershipment',
            name='carrier_type',
            field=models.CharField(choices=[('Rail Car', 'Rail Car'), ('Truck/Trailer', 'Truck/Trailer'), ('Container/Vessel', 'Container/Vessel')], max_length=20),
        ),
    ]
