# Generated by Django 5.0.6 on 2025-04-23 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0022_alter_carrierdetails_carrier_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiversionReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.IntegerField()),
                ('crop_id', models.IntegerField()),
                ('reminder_kept', models.BooleanField(default=True)),
                ('remaining_weight', models.FloatField(blank=True, null=True)),
                ('weight_unit', models.CharField(choices=[('LBS', 'LBS'), ('MT', 'MT')], default='LBS', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
