# Generated by Django 5.0.6 on 2025-04-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0024_processorshipmentdiversionreminder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='customer',
            name='warehouses',
            field=models.ManyToManyField(blank=True, related_name='customers', to='warehouseManagement.warehouse'),
        ),
    ]
