# Generated by Django 5.0.6 on 2025-05-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0025_remove_customer_warehouse_customer_warehouses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemspecification',
            name='lot_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemspecification',
            name='waybill_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
