# Generated by Django 5.0.6 on 2025-08-28 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0026_alter_itemspecification_lot_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrierdetails',
            name='shipment_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processor_shipment_item', to='warehouseManagement.processorshipmentcrops'),
        ),
        migrations.AddField(
            model_name='carrierdetails2',
            name='shipment_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_shipment_item', to='warehouseManagement.warehouseshipmentcrops'),
        ),
    ]
