# Generated by Django 5.0.6 on 2025-08-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0027_carrierdetails_shipment_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processorshipmentcrops',
            name='seal_numbers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='warehouseshipmentcrops',
            name='seal_numbers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
