# Generated by Django 5.0.6 on 2025-09-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0028_processorshipmentcrops_seal_numbers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrierdetails',
            name='additional_equipment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carrierdetails2',
            name='additional_equipment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
