# Generated by Django 5.0.6 on 2025-09-05 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseManagement', '0030_remove_carrierdetails_additional_equipment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalEquipmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_equipment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_equipment_type', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_equipment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processor_shipment_additional_equipment', to='warehouseManagement.processorwarehouseshipment')),
                ('shipment_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processor_customer_shipment_item', to='warehouseManagement.processorshipmentcrops')),
            ],
        ),
    ]
